name: Build

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Minimalistic CLI check
        run: python -u DRipper.py
