name: Build

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

env:
  IMAGE_NAME: alexmon1989/dripper

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Minimalistic CLI check
        run: python -u DRipper.py

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.IMAGE_NAME }}:latest \
            --no-cache --rm .

      - name: Login to Docker Hub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Dockerhub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          docker push ${{ env.IMAGE_NAME }}:latest
