name: Build

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

env:
  IMAGE_NAME: alexmon1989/dripper

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Minimalistic CLI check
        run: python -u DRipper.py

      - name: Get build version
        id: get-version
        run: |
          if test "$(git describe --abbrev=0 --tags 2>/dev/null)"; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            VERSION=master
          fi
          echo ::set-output name=VERSION::$VERSION

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Check available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Configure Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

#      - name: Build Docker image
#        run: |
#          docker build \
#            -t ${{ env.IMAGE_NAME }}:latest \
#            -t ${{ env.IMAGE_NAME }}:${{ steps.get-version.outputs.VERSION }} \
#            --no-cache --rm .

      - name: Login to Docker Hub
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#      - name: Push to Dockerhub
#        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
#        run: |
#          docker push ${{ env.IMAGE_NAME }}:latest
#          docker push ${{ env.IMAGE_NAME }}:${{ steps.get-version.outputs.VERSION }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6
          push: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
